# Generated by Django 3.0.2 on 2020-02-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bangumi',
            fields=[
                ('bangumi_id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('cover_url', models.CharField(blank=True, max_length=100, null=True)),
                ('bangumi_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('vote_num', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('episode_num', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('tags', models.CharField(blank=True, max_length=600, null=True)),
                ('desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('staff_list', models.CharField(blank=True, max_length=3000, null=True)),
                ('cv_list', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'bangumi',
                'managed': False,
            },
        ),
    ]
